-- AlterTable
ALTER TABLE "call" ALTER COLUMN "date_start" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_answer" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "HangupTime" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "Missed" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "empower_stats" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "exports" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);
