-- AlterTable
ALTER TABLE "call" ALTER COLUMN "date_start" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "date_answer" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "HangupTime" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "Missed" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "empower_stats" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "exports" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6);
